// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: (function() {
      const urls = [process.env.TURSO_DATABASE_URL, process.env.DATABASE_URL];
      for (const url of urls) {
        if (url && url !== 'undefined' && url !== 'null' && url.trim() !== '') return url;
      }
      return "file:./dev.db";
    })(),
  },
});
